### ISSUE TITLE
100% volume on Default Device

### ISSUE THREAD

**Issue by psxcode** [nodeful/eqMac2#103] opened 2017-11-26 19:40 UTC
When running eqMac2, the default device gets full volume, even it had different settings.
And if you go to sound settings and lower the volume, and click and switch between devices, the volume on default device gets 100% again
<img width="326" alt="screen shot 2017-11-26 at 20 44 44" src="https://user-images.githubusercontent.com/7700153/33243652-b83082fc-d2ea-11e7-9dc1-028a078a3b30.png">
<img width="702" alt="screen shot 2017-11-26 at 20 44 21" src="https://user-images.githubusercontent.com/7700153/33243653-bc5a69ba-d2ea-11e7-9b4b-fe61ae645181.png">

**Comment by romankisil** [comment] 2017-11-26 20:31
Your default Output device should never be selected when eqMac2 is running. eqMac2 device should always be selected if eqMac2 is functioning correctly. Try restarting your Mac and maybe uninstalling & installing eqMac again.

**Comment by psxcode** [comment] 2017-11-26 22:25
Ok. Of course. But some other sounds eventually come from `Default device`.
This may be, for example, OS sound effects, or others.
The point is that **new version** of `eqMac` keeps volume of `Default device` at **100%**, and you cannot lower it.

**Comment by romankisil** [comment] 2017-11-26 22:27
Ok I see your point. I have my system sound effects turned off so I haven't found that as an issue. I will see what I can do. Thanks for the report

**Comment by romankisil** [comment] 2017-11-26 22:29
Just noticed, you can set the OS sound effect to play through the selected Audio Device
<img width="780" alt="screen shot 2017-11-26 at 22 29 06" src="https://user-images.githubusercontent.com/8472525/33244971-3b3ba65a-d2f9-11e7-8190-56ff39ab89ad.png">

**Comment by psxcode** [comment] 2017-11-26 22:31
Yes. This is possible. But I almost had my ears exploded, when some other sound came from `Default device`, then I tried to lower the sound but `eqMac` holds it at 100%

**Comment by romankisil** [comment] 2017-11-26 22:43
You see, I NEED TO HAVE IT TO 100% :D Otherwise the app won't work.

**Comment by romankisil** [comment] 2017-11-26 22:53
This is because in previous versions I overwrote the entire OSX volume logic and I had full control and was changing the volume of the actual output device. In this release, to keep most users happy, I had to make the eqMac device visible at all times and make it controllable by the OSX native volume controls, therefore I need to set the built-in output device volume to 100% so the end volume is 100% (Built-in) * 20% (eqMac volume) = 20% volume. If I set the volume of built in device the same as eqMac device then the equation will look like 20% (Built-in) * 20% (eqMac volume) = 4% end volume.

**Comment by psxcode** [comment] 2017-11-27 08:15
Hey. Thanks for detailed info. Now I understand.
I had a look at prev implementation.
- previously `eqMac` had no personal volume control and everything worked through `Main Volume control`
- now it has its own volume control, that is being multiplied by `Main Volume control`, so `Main` is forced to **100%** during running, and restored when quit
This approach solves some problems, and the only con I found, is that some app could push the sound through the `Default Device` and it will be VERY loud.
But again.
Thank you for **developing** and **supporting** this project, keeping it **FREE**.
**BIG THANKS** from all of us

**Comment by TheBay0r** [comment] 2017-11-27 15:11
I have the feeling this one is related:
I have my default device muted (usually). But when I close my macbook and open it later, it resets to 100% volume. So everytime I send my machine to sleep, it resets my audio settings.

**Comment by uner** [comment] 2017-11-27 23:43
The problem as I see it is that when you launch eqMac 2.1, it changes the output device to "eqMac2," but changes the Sound Effects output selection to whatever it was before. 

So prior to launch, I have the output selection as "Headphones" and Sound Effects' "Play sound effects through" is set to "Selected Sound output device."

When I launch eqMac2, the output selection switched to "eqMac2," and Sound Effects' "Play sound effects through" is set to "Headphones."

So if somehow the Sound Effects output device could also be set to eqMac2, I think we'd be good to go for alert sounds. But as it is, each time you launch the app, you must go into the sound preferences and change it manually if you don't want to jump out of your chair when the first system alert sound plays.

**Comment by SwissDutch** [comment] 2017-11-28 16:11
Please give me back the previous version!! This is a health hazard!!! It really blows our ears out!! This is dangerous!!

Thank you very much for the very good work but it is unacceptable that the volume EVER goes to 100%!!

Let me know how I can install the previous version: THIS ONE WAS PERFECT!!!!

**Comment by psxcode** [comment] 2017-11-28 16:38
@SwissDutch 
[Releases](https://github.com/romankisil/eqMac2/releases)
Download any `.dmg` you want

**Comment by SwissDutch** [comment] 2017-11-28 19:23
@psxcode: thank you very much!!! To be sure: the prior version was Build 2.0.6?

**Comment by romankisil** [comment] 2017-11-28 19:37
Yes the previous version is 2.0.6
I will fix the volume in the next update

**Comment by SwissDutch** [comment] 2017-11-28 21:08
@romankisil Thank you very much for the info. I took the previous version for now (to save my ears). But your equalizer is really super!!!! As soon as you got it fixed I will again take the latest version. Keep up the good work!!

**Comment by easdale** [comment] 2017-11-29 16:24
I have a similar thing happen. When I'm listening to the audio in a film played through my browser its all ok and controllable but I go to my adobe premiere pro app the volume is playing back at 100%!
Even if I turn my system volume down to ZERO I am still getting 100% volume out of my external speakers.
Then I pulled the wire out from the computer to see if this was happening from the internal speakers and I could then control the volume level BUT it still sounds like its playing back at full volume but just a lower level so I can hear the distortion you would get from having an amp driven at full blast and the distortion that comes with that.
I then plugged my external cable back in and I have volume control but I still get massive distortion in the audio when using premiere pro so I can't edit films anymore with your software. The browser audio sounds as it should. 
Can you fix this issue with premiere pro?

**Comment by i34756** [comment] 2017-11-29 21:47
I immediately uninstalled the new version eqmac2 after the update. I understood your purpose but 100% system volume setting is giving me so many annoying issues. I have to hear full volumed startup sound everytime I turn on my macbook, full volumed music occasionally while adjusting settings and full volumed notifications. Please don't make everything annoying to respond a few complaint.

**Comment by qoolqat** [comment] 2017-12-01 21:19
Just want to chime in that I also had my ears blown out by an unexpected sound at 100%, very painful and potentially damaging experience.  Great project, but am uninstalling for now.

**Comment by nodeful** [comment] 2017-12-02 23:31
I have release an update (Build 2.2) Please update and tell me if the issue is still relevant. Thanks

**Comment by uner** [comment] 2017-12-02 23:59
This build fixed the issue for me. I tested various configurations of using the built-in output with and without headphones, the display audio, and various combos thereof for sound effects. Rock solid as far as I can tell - thank you!!!

**Comment by SwissDutch** [comment] 2017-12-04 14:34
This fixed the problem for me and all the functionality is back (and my ears are still alive :-)). Thanks a million!!!!

**Comment by nodeful** [comment] 2017-12-04 14:49
Cool, I guess I can close this one :) Cheers guys

**Closed by nodeful** 2017-12-04 14:49 UTC

**Comment by qoolqat** [comment] 2017-12-04 16:15
Thanks, reinstalled, sounds good so far. Appreciate the rapid response. Donated to the project.

**Comment by asaada83** [comment] 2017-12-04 20:04
@nodeful doesn't seem to be fixed for me 😞 . Still jumps to 100% on device switch. Headphones/Internal Speakers etc..
I even tried to uninstall and re-install still jumps to 100%.. I'm using Build v2.2 on MBP Sierra 10.12.6

**Comment by uner** [comment] 2017-12-04 20:22
@asaada83 - I noticed it jumped the *first* time I switched, after I had adjusted the volume for each output, it retained the volume each time. Can you go through all the combos with eqMac2 not running, set them to some lower value, then launch eqMac2? That works perfectly for me on High Sierra. Also, keep in mind some transitions change the volume even without eqMac2 installed. For example, on my Sierra MBP, if I have headphones in and then connect to my external display, the volume of the headphones jumps to whatever it was the last time I had the display plugged in. I think macOS "remembers" various configurations and tries to do you a favor - whether you want it to or not.

**Comment by asaada83** [comment] 2017-12-04 20:48
I tried that just now. Still doesn't work. I use the sound settings in the MacOS system preferences to switch devices. 
I only use the headphones jack and the internal speakers for now. Not other external audio sources.

Also I noticed that if I unplug the headphones it doesn't automatically switch to the internal speakers I have to reselect them for the sound to work.

**Comment by qoolqat** [comment] 2017-12-13 19:37
Ok, eqMac2 stopped working and suddenly the volume jumped to 100% again, blasting my ears out again. There won't be a 3rd time.

**Comment by uner** [comment] 2017-12-13 20:00
@qoolqat Can you let us know what you do to reproduce this? I have a pretty complicated setup couching daily between headphones, speakers, and internal speakers while mobile, and it's been rock solid. But I am happy to try and reproduce this by following your workflow if it helps.

**Comment by qoolqat** [comment] 2017-12-13 20:11
I'm assuming the app crashed in some way. There was no sound, and when i adjusted the volume (F11/F12), there remained no sound... i clicked on the eqmac2 icon in the menu bar and the icon disappeared and the sound jumped to 100%. There were no steps that I could reproduce, it happened randomly.

**Comment by asaada83** [comment] 2017-12-13 20:12
Maybe is OS specific? Sounds like it's working fine for people with High Sierra but I'm on Sierra 10.12.6 and this never worked for me as expected.

**Comment by nodeful** [comment] 2017-12-14 00:06
Well there is no other way to NOT have the volume of the Built-in Device on 100%, explained it many times. I am moving to a much more modern driver in the next release (probably coming out in a couple months) so I will have more control over these annoying bugs. Sorry for the issues

**Comment by alexdoub** [comment] 2018-02-22 17:52
Hi guys, same issue happened to me for the last time now. I gotta find other software that won't blow my freaking head off when I change the settings.

Seriously, fix this. AFAIK I'm using the latest version and its still happening. For the love of christ, at least add a "max volume" option in the settings that would prevent the volume from going past X percent.

**Comment by Jaribeau** [comment] 2018-03-28 03:50
Echoed, issue is still prevalent on El Cap and has blasted crazy volumes into my ears on numerous occasions now. Will update to High Sierra when I can to see if that makes a difference.

I love the work you've been doing otherwise though, but will have to switch back to an old version for the time being. Thanks for your time and effort!

**Comment by ngoclt** [comment] 2018-04-17 09:11
This happens to my MAC Sierra, when the output device is changed the volume jumps to maximum :( Please fix, it hurts my ear a lot.

**Comment by ddayan** [comment] 2018-07-29 13:14
As others said this is a health hazard and also it might have ruined my iems :/

**Comment by JCruz8482** [comment] 2018-08-15 02:52
Until this issue is resolved, maybe you can add a warning in a very obvious place. It's kind of ridiculous that I had to blow my ears out to find out about this issue.

**Comment by verekia** [comment] 2018-09-15 12:43
This is extremely dangerous and can cause permanent hearing damage. I was very lucky that the very loud sound that came out was a soft song intro, but it still hurt my ears a lot.

**Comment by SwissDutch** [comment] 2018-09-20 11:14
I thought this ear-blowing issue was resolved with release 2.2. It indeed now seems to be back. Do I need to revert back to release 2.06?

Please let us know if the ear-blowing issue is back.

**Comment by bostrom** [comment] 2018-09-27 05:52
I agree, this needs to be fixed! The volume goes up to 100% each time i switch devices.

**Comment by hasuf** [comment] 2018-10-09 17:03
> Well there is no other way to NOT have the volume of the Built-in Device on 100%, explained it many times. I am moving to a much more modern driver in the next release (probably coming out in a couple months) so I will have more control over these annoying bugs. Sorry for the issues

Is there a new ticket for incorporating the new driver?

**Comment by Lumpenstein** [comment] 2018-10-23 08:33
Hey so what is the workaround at the moment ? I'm trying to use eqMac2 with GooglePlayMusicDesktopPlayer, if I'm chosing audio device default or eqMac2 in GPMDP there is no sound at all, if I'm chosing built-in audio the volume jumps to 100% and neither MacOs sound setting nor the volume slider in the eqMac2 window change the volume, only the volume sliders in the programs emitting the sounds are affecting volume...

**Comment by somanyusers** [comment] 2019-02-07 23:41
This is still an issue in v2.2 - downright dangerous.  I backgraded to v2.06, but the whole mess sure shakes one's confidence in using this app safely.

**Comment by alexdoub** [comment] 2019-02-07 23:58
Someone should fork this and just do the change themselves. One day if I got time I'll do it. I doubt its that hard

**Comment by Lumpenstein** [comment] 2019-02-08 07:02
To everyone having problems with the sound:

I got everything working properly by selecting eqMac2 as Audio device in my player of choice.
That moment I was getting no sound at all. I needed to go to system preferences/sound/input and set the input volume to max for the eqMac2 input (not the internal mic). Under output device eqMac2 should be automatically selected.
Afterwards it's working as intended, volume sliders are working, no jumping to 100% etc.

**Comment by SwissDutch** [comment] 2019-04-15 07:49
Hello Roman,

I have never had the 100% volume issue again (although I am careful now
:-)).
The issue I have now is that eqmac2 often drains up to 32% of the energy of
my laptop for extended periods of time. Do you know what the reason for
this is?

Thanks, Olivier

**Comment by nodeful** [comment] 2020-01-08 20:40
Hey everyone. Excuse me for the lack of updates. I have been really busy on the new version of eqMac. I am happy to announce an open beta release. 
You can download it here: https://eqmac.app
There are a lot of known bugs that I could not fix just yet:

- Driver not installing from the first try. Sometimes need to restart eqMac a couple times.
- Complex Device switching logic is not perfect (for example when switching off the device that's currently playing, plugging in new device etc.)
- UI takes long to load (a lot can be done to improve that)
- UI dimensions are not synching properly
- There's a noticeable audio delay in the playback, so not suitable for video yet (I know where the problem lies just haven't had the time to fix yet)
- Sometimes the playback doesn't start, in that case please try to switch the output to the device you want and eqMac should try and build the audio pipeline again.

So as you can see there's still some work to be done but at least it's a completely modern tech stack that I am fully willing to work on: 100% Swift, User Space driver and a Web UI, instead of C++, Kernel Drivers. As I said, should work on Catalina and should not have any pesky ear drum blasting volume bugs (at least I didn't come across any).
I'm open to feedback and issue reports here: https://github.com/bitgapp/eqmac
That repo will become the main repo for eqMac and this repo will be archived eventually.
And yes it's called just eqMac, not eqMac3 :) And it will stay that way forever.

**Comment by Jaribeau** [comment] 2020-01-08 20:48
Thanks for your work on this @nodeful! I'll install the latest version when I get a chance and offer what helpful feedback that I can.

**Comment by nodeful** [comment] 2020-04-04 16:38
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.
